name: feeding_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  fonts: 
    - family: RobotoSlab
      fonts: 
        - asset: lib/assets/fonts/RobotoSlab-VariableFont_wght.ttf
    
    - family: DancingScript
      fonts: 
        - asset: lib/assets/fonts/DancingScript-VariableFont_wght.ttf

  assets: 
    - lib/assets/images/sign_up.jpg
  uses-material-design: true

